[versions]
# Platform expectations
spigot = "1.21.8-R0.1-SNAPSHOT"
paperlib = "1.0.8"

# Plugins
luckperms = "5.5"
worldedit = "7.4.0"
placeholderapi = "2.12.2"
axiompaper = "4.0.1-1.21.1"
# Third Party
annotations = "26.0.2-1"
authlib = "3.13.56"
aws-sdk = "2.41.19"
bouncycastle = "1.83"
bstats = "3.1.0"
fastboard = "2.1.5"
jspecify = "1.0.0"
nbt = "1.5.1"
sshd-sftp = "2.17.1"
xseries = "13.6.0"
zip4j = "2.11.6"

[libraries]
# Platform expectations
spigot = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot" }
paperlib = { group = "io.papermc", name = "paperlib", version.ref = "paperlib" }

# Plugins
luckperms = { group = "net.luckperms", name = "api", version.ref = "luckperms" }
placeholderapi = { group = "me.clip", name = "placeholderapi", version.ref = "placeholderapi" }
worldedit = { group = "com.sk89q.worldedit", name = "worldedit-core", version.ref = "worldedit" }
axiompaper = { group = "maven.modrinth.workaround", name = "axiom-paper-plugin", version.ref = "axiompaper" }

# Third Party
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
authlib = { group = "com.mojang", name = "authlib", version.ref = "authlib" }
aws-auth = { module = "software.amazon.awssdk:auth", version.ref = "aws-sdk" }
aws-core = { module = "software.amazon.awssdk:core", version.ref = "aws-sdk" }
aws-regions = { module = "software.amazon.awssdk:regions", version.ref = "aws-sdk" }
aws-s3 = { module = "software.amazon.awssdk:s3", version.ref = "aws-sdk" }
bouncycastle = { group = "org.bouncycastle", name = "bcpkix-jdk18on", version.ref = "bouncycastle" }
bstats = { group = "org.bstats", name = "bstats-bukkit", version.ref = "bstats" }
fastboard = { group = "fr.mrmicky", name = "fastboard", version.ref = "fastboard" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
nbt = { group = "dev.dewy", name = "nbt", version.ref = "nbt" }
sftp = { group = "org.apache.sshd", name = "sshd-sftp", version.ref = "sshd-sftp" }
zip4j = { group = "net.lingala.zip4j", name = "zip4j", version.ref = "zip4j" }
xseries = { group = "com.github.cryptomorin", name = "XSeries", version.ref = "xseries" }

[bundles]
aws = [
    "aws-s3",
    "aws-auth",
    "aws-regions",
    # "aws-core", Unable to find the dependency at runtime
]