[versions]
# Platform expectations
spigot = "1.21.5-R0.1-SNAPSHOT"
paperlib = "1.0.8"

# Plugins
luckperms = "5.5"
worldedit = "7.2.20"
placeholderapi = "2.11.6"
axiompaper = "4.0.1-1.21.1"
# Third Party
annotations = "26.0.2"
authlib = "1.5.25"
bstats = "3.1.0"
fastboard = "2.1.4"
nbt = "1.5.1"
xseries = "13.3.1"

[libraries]
# Platform expectations
spigot = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot" }
paperlib = { group = "io.papermc", name = "paperlib", version.ref = "paperlib" }

# Plugins
luckperms = { group = "net.luckperms", name = "api", version.ref = "luckperms" }
placeholderapi = { group = "me.clip", name = "placeholderapi", version.ref = "placeholderapi" }
worldedit = { group = "com.sk89q.worldedit", name = "worldedit-core", version.ref = "worldedit" }
axiompaper= {group = "maven.modrinth.workaround", name = "axiom-paper-plugin", version.ref="axiompaper"}

# Third Party
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
authlib = { group = "com.mojang", name = "authlib", version.ref = "authlib" }
bstats = { group = "org.bstats", name = "bstats-bukkit", version.ref = "bstats" }
fastboard = { group = "fr.mrmicky", name = "fastboard", version.ref = "fastboard" }
nbt = { group = "dev.dewy", name = "nbt", version.ref = "nbt" }
xseries = { group = "com.github.cryptomorin", name = "XSeries", version.ref = "xseries" }